# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 46e68b875cb5f15b884b85628fff5ce92a7ae3414b158b2cb5fe0f457038d0fa6e454544d8140a7b5f7cd75afac031ff73f79ec122a816abf09e3890df96f2c9

test:
  secret_key_base: d5f5c9edec73accf0cc3e72dcdcc1ee58bae5cf2df82f0bb1789f6267121a5803ae28babda6fefe1b5cdea48891600ebdc41867f92939757f322e7c0b22044ec

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
